/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DB_Connection.*;
import static Interfaces.GetKeyStroke.getKey;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import sun.security.action.GetBooleanAction;

/**
 *
 * @author Thilina Prasad
 */
public class LogIn extends javax.swing.JFrame {

    ArrayList<Long> pressed_int = new ArrayList<>();
    ArrayList<Long> fly_int = new ArrayList<>();
    ArrayList<Long> total_time = new ArrayList<>();
    long pressed_time = 0;
    long released_time = 0;
    String uName = "";

    /**
     * Creates new form Main
     */
    public LogIn() {
        initComponents();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userName1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userName2 = new javax.swing.JTextField();
        logInBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Key Stroke | LogIn");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        userName1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userName1ActionPerformed(evt);
            }
        });
        userName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userName1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userName1KeyReleased(evt);
            }
        });

        jLabel4.setText("User Name                :");

        jLabel5.setText("Re-Type User Name :");

        userName2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userName2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userName2FocusGained(evt);
            }
        });
        userName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userName2ActionPerformed(evt);
            }
        });
        userName2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userName2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userName2KeyReleased(evt);
            }
        });

        logInBtn.setText("Log In");
        logInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logInBtnMouseClicked(evt);
            }
        });

        jButton2.setText("Sign Up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Reset");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(userName2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(userName1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logInBtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logInBtn)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetField(){
        userName1.setText(null);
        userName2.setText(null);
        uName = "";
        pressed_int.clear();
        fly_int.clear();
        total_time.clear();
        pressed_time = 0;
        released_time = 0;
    }
    
    private void userName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userName1ActionPerformed

    private void userName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userName2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GetKeyStroke getKey = new GetKeyStroke();
        getKey.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public double compareValues(double original, double enterd) {
        double variying = Math.abs(original - enterd);
        double presntage = (variying / original) * 100;
        return presntage;
    }

    private void logInBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInBtnMouseClicked
        if (userName1.getText().length() != 0 && userName2.getText().length() != 0) {
            if (userName1.getText().equals(userName2.getText())) {
                uName = userName1.getText();

                long totTime = 0;
                int size = uName.length();
                int arrayLength = pressed_int.size();
                for (int i = 0; i < size; i++) {
                    totTime += (pressed_int.subList(arrayLength - size, arrayLength).get(i) + fly_int.subList(arrayLength - size, arrayLength).get(i));
                }
                total_time.add(totTime);

                DBDataHandel dbData = new DBDataHandel();
                ArrayList<String> results = dbData.getData(uName);
                if (results.size() != 0) {
                    double storedpressed = Double.parseDouble(results.get(2));
                    double storedfly = Double.parseDouble(results.get(3));
                    double storedtot = Double.parseDouble(results.get(4));
                    
                     double loginpressed = GetKeyStroke.calcAvg(pressed_int);
                    double loginfly = GetKeyStroke.calcAvg(fly_int);
                    double logintot = GetKeyStroke.calcAvg(total_time);
                    double pressdChec = compareValues(storedpressed,loginpressed );
                    double flyCheck = compareValues(storedfly, loginfly);
                    double totCheck = compareValues(storedtot,logintot );

                    System.out.println(pressdChec);
                    System.out.println(flyCheck);
                    System.out.println(totCheck);
                    if (pressdChec <= 20 && flyCheck <= 20 && totCheck <= 15) {
                        String newPressed = Double.toString((storedpressed*10+loginpressed)/11.0);
                        String newFly = Double.toString((storedfly*10+loginfly)/11.0);
                        String newTot = Double.toString((storedtot*10+logintot)/11.0);
                        dbData.updateData(uName, newPressed, newFly, newTot);
                        User user = new User(results);
                        user.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Invalid User credetials!", "  Attention", JOptionPane.WARNING_MESSAGE);
                        resetField();
                    }
                    //System.out.println(total_time.size());
                    // System.out.println(GetKeyStroke.calcAvg(total_time));
                    //System.out.println(results.get(4));
                } else {
                    JOptionPane.showMessageDialog(this, "User Not Found!\nPlease register to the system!", "  Attention", JOptionPane.WARNING_MESSAGE);
                    resetField();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Entered User Names are doesn't equal!", "  Attention", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill username in both field before press 'Log In'", "  Attention", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_logInBtnMouseClicked

    private void userName1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userName1KeyPressed
//        if()
        if (getKey(evt).length() == 1 && getKey(evt) != "Backspace" && getKey(evt) != "Space" && getKey(evt) != "Shift" && getKey(evt) != "Delete") {
            //System.out.println("In");
            pressed_time = System.currentTimeMillis();
            if (released_time != 0) {
                fly_int.add(pressed_time - released_time);
            } else {
                fly_int.add(released_time);
            }
        } else {
            for (int i = 0; i < userName1.getText().length(); i++) {
                pressed_int.remove(pressed_int.size() - 1);
                fly_int.remove(fly_int.size() - 1);
            }
            pressed_time = 0;
            released_time = 0;
            userName1.setText(null);
            System.out.println(pressed_int.toString());
            System.out.println(fly_int.toString());
        }

    }//GEN-LAST:event_userName1KeyPressed

    private void userName1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userName1KeyReleased

        if (getKey(evt).length() == 1 && getKey(evt) != "Backspace" && getKey(evt) != "Space" && getKey(evt) != "Shift" && getKey(evt) != "Delete") {
            //System.out.println("In");
            released_time = System.currentTimeMillis();
            pressed_int.add(released_time - pressed_time);
        }
    }//GEN-LAST:event_userName1KeyReleased

    private void userName2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userName2KeyReleased
        if (getKey(evt).length() == 1 && getKey(evt) != "Backspace" && getKey(evt) != "Space" && getKey(evt) != "Shift" && getKey(evt) != "Delete") {
            //System.out.println("In");
            released_time = System.currentTimeMillis();
            pressed_int.add(released_time - pressed_time);
        }
    }//GEN-LAST:event_userName2KeyReleased

    private void userName2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userName2KeyPressed
        if (getKey(evt).length() == 1 && getKey(evt) != "Backspace" && getKey(evt) != "Space" && getKey(evt) != "Shift" && getKey(evt) != "Delete") {
            //System.out.println("In");
            pressed_time = System.currentTimeMillis();
            if (released_time != 0) {
                fly_int.add(pressed_time - released_time);
            } else {
                fly_int.add(released_time);
            }
        } else {
            for (int i = 0; i < userName2.getText().length(); i++) {
                pressed_int.remove(pressed_int.size() - 1);
                fly_int.remove(fly_int.size() - 1);
            }
            pressed_time = 0;
            released_time = 0;
            userName2.setText(null);
            System.out.println(pressed_int.toString());
            System.out.println(fly_int.toString());
        }
    }//GEN-LAST:event_userName2KeyPressed

    private void userName2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userName2FocusGained
        pressed_time = 0;
        released_time = 0;
        if (userName1.getText().length() != 0 & total_time.isEmpty()) {
            long totTime = 0;
            for (int i = 0; i < userName1.getText().length(); i++) {
                totTime += (pressed_int.get(i) + fly_int.get(i));
            }
            total_time.add(totTime);
        }
    }//GEN-LAST:event_userName2FocusGained

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        resetField();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logInBtn;
    private javax.swing.JTextField userName1;
    private javax.swing.JTextField userName2;
    // End of variables declaration//GEN-END:variables
}
