/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.util.ArrayList;

/**
 *
 * @author Thilina Prasad
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form user
     */
    static ArrayList<String> userdata;
    public User(ArrayList<String> userdata) {
        initComponents();
        this.userdata = userdata;
        name.setText(userdata.get(1));
        presssingTime.setText(userdata.get(2));
        flyingTime.setText(userdata.get(3));
        totTime.setText(userdata.get(4));
        fNamelbl.setText(userdata.get(5));
        agelbl.setText(userdata.get(6));
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        presssingTime1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uName = new javax.swing.JLabel();
        uName1 = new javax.swing.JLabel();
        uName2 = new javax.swing.JLabel();
        uName3 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        presssingTime = new javax.swing.JLabel();
        flyingTime = new javax.swing.JLabel();
        totTime = new javax.swing.JLabel();
        uName4 = new javax.swing.JLabel();
        fNamelbl = new javax.swing.JLabel();
        uName5 = new javax.swing.JLabel();
        agelbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        presssingTime1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        presssingTime1.setText("Name :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Key Stroke | Home");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/user-male-icon.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("ThunaivanTSC", 1, 18)); // NOI18N
        jLabel2.setText("User Data");

        uName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        uName.setText("User Name :");

        uName1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        uName1.setText("Key Pressing Time :");

        uName2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        uName2.setText("Total Time :");

        uName3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        uName3.setText("Flying Time :");

        name.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        name.setText("**************");

        presssingTime.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        presssingTime.setText("****************");

        flyingTime.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        flyingTime.setText("*******************");

        totTime.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        totTime.setText("*******************");

        uName4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        uName4.setText("Full Name :");

        fNamelbl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        fNamelbl.setText("**************");

        uName5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        uName5.setText("Age :");

        agelbl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        agelbl.setText("**************");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/if_logout_59175.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uName5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uName1)
                                    .addComponent(uName)
                                    .addComponent(uName4)
                                    .addComponent(uName3)
                                    .addComponent(uName2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totTime)
                                    .addComponent(flyingTime)
                                    .addComponent(fNamelbl)
                                    .addComponent(name)
                                    .addComponent(presssingTime)
                                    .addComponent(agelbl))))
                        .addContainerGap(75, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uName4)
                            .addComponent(fNamelbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uName5)
                            .addComponent(agelbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uName)
                            .addComponent(name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uName1)
                            .addComponent(presssingTime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uName3)
                            .addComponent(flyingTime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uName2)
                            .addComponent(totTime))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        LogIn logIn = new LogIn();
        logIn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel3MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User(userdata).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agelbl;
    private javax.swing.JLabel fNamelbl;
    private javax.swing.JLabel flyingTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel presssingTime;
    private javax.swing.JLabel presssingTime1;
    private javax.swing.JLabel totTime;
    private javax.swing.JLabel uName;
    private javax.swing.JLabel uName1;
    private javax.swing.JLabel uName2;
    private javax.swing.JLabel uName3;
    private javax.swing.JLabel uName4;
    private javax.swing.JLabel uName5;
    // End of variables declaration//GEN-END:variables
}
